var videoList = [
    'Aerial Neighborhood Video.mp4',
    'Bike Messenger 1.mp4',
    'Bike Messenger 2.mp4',
    'Bike Messenger 3.mp4',
    'E1 Cruising Lake Erie with Suzuki Intruder.mp4',
    'E2 Hang Gliding Rio.mp4',
    'E3 Horseback Riding 1.mp4',
    'E4 Snowboarding.mp4',
    'E5 Wind Surfing 1.mp4',
    'Glide Mountains Slow.mp4',
    'H0 Sky Dive Mont Blanc 2.mp4',
    'H1 Best Kroger.mp4',
    'H2 BMX riding in NYC.mp4',
    'H3 Extreme Paragliding.mp4',
    'H4 Launch Paragliding.mp4',
    'H5 New York bus ride from window.mp4',
    'H6 Venetian Foyer.mp4',
    'H7 Train Tunnel.mp4',
    'H8 Walking in Times Square.mp4',
    'H9 Mountain biking in the woods.mp4',
    'M1 Motorcycling Fast.mp4',
    'M2 High Speed Canyon Jet Ski.mp4',
    'M3 Navy Seals Jump.mp4',
    'M4 Typhoon Mach Loop.mp4',
    'M5 Hang Gliding Snowy Mountains 2.mp4',
    'N0 Bellagio Water Show.mp4',
    'N1 Hang Gliding Snowy Mountains 1.mp4',
    'N2 Army 82 Airborne Parachute Drop.mp4',
    'N3 Hot Air Ballooning.mp4',
    'N4 Wing Suit Flight.mp4',
    'N5 Driving in Amish Country.mp4',
//    'N6 Scuba Diving.mp4', //Old version. Do not include.
    'N6 Scuba Diving Edited.mp4',
    'N7 Snorkeling Sardinia.mp4',
//    'N8 Lake Sunset.mp4', //Old version. Do not include.
    'N8 LakeSunset.mp4',
    'N9 Ice Climbing.mp4',
    'Paraglide Neutral.mp4',
    'Paraglide Spin Lamellar.mp4',
    'Walking Japan 1.mp4',
    'Walking Japan 2.mp4',
    'Walking Japan 3.mp4', 
    'Walking Japan 4.mp4',
];